### ISSUE TITLE
Can't post anything because the "post" button's bar is being covered by the upper top bar

### ISSUE THREAD

**Issue by aocorporation** [moffatman/chan#197]
![image](https://github.com/moffatman/chan/assets/140784925/58c9a727-c1f8-4eef-b595-7142c40bc272)

Latest version
iPhone XR (also latest version)

**Comment by moffatman** [comment]
Somehow you dragged the reply box too big. I must have changed the sizes of things in the last update so that your reply box which was really close to the top got too big now?
My suggestion to fix
1. Reduce interface scale in appearance settings until you can see the post buttons etc
2. Drag the top of the reply form down to shrink it
3. Increase interface scale back to the original value
4. Drag the top of the reply form to your appropriate size

Thanks for your patience!

**Comment by aocorporation** [comment]
Fixed! Thank you just had to reset interface to 95 back to 100
